#!/bin/sh
# iVentoy service setup script for DSM
PKG_TARGET="${SYNOPKG_PKGDEST}"
PKG_VAR="${SYNOPKG_PKGVAR}"
WRAPPER="${PKG_TARGET}/iventoy-wrapper.sh"

IVENTOY_CONF="${PKG_VAR}/iventoy.conf"
NGINX_CONF="${PKG_TARGET}/nginx/iventoy.conf"
NGINX_HTPASSWD="${PKG_VAR}/htpasswd"

SERVICE_COMMAND="${WRAPPER} -R start"
SVC_BACKGROUND=y
SVC_WRITE_PID=y

GROUP="sc-iventoy"

read_config() {
    if [ -f "${IVENTOY_CONF}" ]; then
        . "${IVENTOY_CONF}"
    fi
    : ${IVENTOY_ISO_DIR:="/volume1/ISO/iVentoy"}
    : ${IVENTOY_WEB_PORT:=26000}
}

link_var_dirs() {
    for d in data driver user log; do
        mkdir -p "${PKG_VAR}/$d"
        if [ -d "${PKG_TARGET}/$d.init" ]; then
            cp -rn "${PKG_TARGET}/$d.init/." "${PKG_VAR}/$d/" 2>/dev/null || true
        fi
        if [ -d "${PKG_TARGET}/$d" -a ! -L "${PKG_TARGET}/$d" ]; then
            rm -rf "${PKG_TARGET}/$d"
        fi
        ln -sfn "${PKG_VAR}/$d" "${PKG_TARGET}/$d"
    done

    mkdir -p "${PKG_VAR}/log/client" "${PKG_VAR}/log/history"
    if [ -d "${PKG_TARGET}/log" -a ! -L "${PKG_TARGET}/log" ]; then
        rm -rf "${PKG_TARGET}/log"
    fi
    ln -sfn "${PKG_VAR}/log" "${PKG_TARGET}/log"

    mkdir -p "${IVENTOY_ISO_DIR}"
    chmod 755 "${IVENTOY_ISO_DIR}"
    if [ -d "${PKG_TARGET}/iso" -a ! -L "${PKG_TARGET}/iso" ]; then
        rm -rf "${PKG_TARGET}/iso"
    fi
    ln -sfn "${IVENTOY_ISO_DIR}" "${PKG_TARGET}/iso"
}

generate_config() {
    cat > "${IVENTOY_CONF}" <<EOF
# iVentoy Configuration - Generated by DSM package wizard
# Do not edit manually; changes will be overwritten on upgrade
# To change ISO path, edit this file and restart the package

IVENTOY_ISO_DIR="${wizard_iso_path}"
IVENTOY_WEB_PORT=26000
IVENTOY_BIND_ADDR=127.0.0.1
IVENTOY_DHCP_ENABLE=1
IVENTOY_TFTP_ENABLE=1
IVENTOY_HTTP_ENABLE=1
IVENTOY_NBD_ENABLE=1
IVENTOY_ISCSI_ENABLE=1
IVENTOY_NFS_ENABLE=1
EOF
    chmod 644 "${IVENTOY_CONF}"
}

generate_nginx_config() {
    mkdir -p "${PKG_TARGET}/nginx"

    if [ -n "${wizard_username}" -a -n "${wizard_password}" ]; then
        "${PKG_TARGET}/nginx/generate_htpasswd.sh" "${wizard_username}" "${wizard_password}" "${NGINX_HTPASSWD}"
        AUTH_CONFIG="auth_basic \"iVentoy Web UI\";\n    auth_basic_user_file ${NGINX_HTPASSWD};"
    else
        AUTH_CONFIG="# No authentication configured"
    fi

    cat > "${NGINX_CONF}" <<EOF
# iVentoy nginx reverse proxy configuration
# Generated by DSM package - do not edit manually

server {
    listen 127.0.0.1:26001;
    server_name localhost;

    add_header X-Frame-Options DENY;
    add_header X-Content-Type-Options nosniff;
    add_header X-XSS-Protection "1; mode=block";

    ${AUTH_CONFIG}

    location / {
        proxy_pass http://127.0.0.1:26000;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;

        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection "upgrade";

        proxy_connect_timeout 60s;
        proxy_send_timeout 60s;
        proxy_read_timeout 60s;
    }
}
EOF
}

block_internal_port() {
    iptables -C INPUT -i lo -p tcp --dport 26000 -j ACCEPT 2>/dev/null || \
        iptables -I INPUT -i lo -p tcp --dport 26000 -j ACCEPT
    iptables -C INPUT ! -i lo -p tcp --dport 26000 -j DROP 2>/dev/null || \
        iptables -I INPUT ! -i lo -p tcp --dport 26000 -j DROP
}

unblock_internal_port() {
    iptables -D INPUT -i lo -p tcp --dport 26000 -j ACCEPT 2>/dev/null || true
    iptables -D INPUT ! -i lo -p tcp --dport 26000 -j DROP 2>/dev/null || true
}

service_postinst() {
    if [ "${SYNOPKG_PKG_STATUS}" == "INSTALL" ]; then
        generate_config
        generate_nginx_config
        link_var_dirs
    fi
}

service_prestart() {
    read_config
    link_var_dirs
    if [ ! -f "${NGINX_CONF}" ]; then
        generate_nginx_config
    fi
    export LD_LIBRARY_PATH="${PKG_TARGET}/lib:${LD_LIBRARY_PATH}"
    block_internal_port
}

service_poststart() {
    if [ -x /usr/syno/sbin/nginx ]; then
        ln -sf "${NGINX_CONF}" /etc/nginx/sites-enabled/iventoy.conf 2>/dev/null || true
        /usr/syno/sbin/nginx -s reload 2>/dev/null || true
    fi
}

service_stop() {
    rm -f /etc/nginx/sites-enabled/iventoy.conf 2>/dev/null
    /usr/syno/sbin/nginx -s reload 2>/dev/null || true
    unblock_internal_port
    ${WRAPPER} stop
}

service_preupgrade() {
    mkdir -p "${SYNOPKG_TEMP_UPGRADE_FOLDER}/backup"
    cp -p "${IVENTOY_CONF}" "${SYNOPKG_TEMP_UPGRADE_FOLDER}/backup/" 2>/dev/null || true
    cp -p "${NGINX_HTPASSWD}" "${SYNOPKG_TEMP_UPGRADE_FOLDER}/backup/" 2>/dev/null || true
    cp -p "${PKG_VAR}/data/iventoy.dat" "${SYNOPKG_TEMP_UPGRADE_FOLDER}/backup/" 2>/dev/null || true
    cp -p "${PKG_VAR}/data/mac.db" "${SYNOPKG_TEMP_UPGRADE_FOLDER}/backup/" 2>/dev/null || true
}

service_postupgrade() {
    if [ -f "${SYNOPKG_TEMP_UPGRADE_FOLDER}/backup/iventoy.conf" ]; then
        cp -p "${SYNOPKG_TEMP_UPGRADE_FOLDER}/backup/iventoy.conf" "${IVENTOY_CONF}"
    fi
    if [ -f "${SYNOPKG_TEMP_UPGRADE_FOLDER}/backup/htpasswd" ]; then
        cp -p "${SYNOPKG_TEMP_UPGRADE_FOLDER}/backup/htpasswd" "${NGINX_HTPASSWD}"
    fi
    if [ -f "${SYNOPKG_TEMP_UPGRADE_FOLDER}/backup/iventoy.dat" ]; then
        cp -p "${SYNOPKG_TEMP_UPGRADE_FOLDER}/backup/iventoy.dat" "${PKG_VAR}/data/"
    fi
    if [ -f "${SYNOPKG_TEMP_UPGRADE_FOLDER}/backup/mac.db" ]; then
        cp -p "${SYNOPKG_TEMP_UPGRADE_FOLDER}/backup/mac.db" "${PKG_VAR}/data/"
    fi
    generate_nginx_config
    link_var_dirs
}